# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import xee_pb2 as xee__pb2

GRPC_GENERATED_VERSION = '1.65.1'
GRPC_VERSION = grpc.__version__
EXPECTED_ERROR_RELEASE = '1.66.0'
SCHEDULED_RELEASE_DATE = 'August 6, 2024'
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    warnings.warn(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in xee_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
        + f' This warning will become an error in {EXPECTED_ERROR_RELEASE},'
        + f' scheduled for release on {SCHEDULED_RELEASE_DATE}.',
        RuntimeWarning
    )


class PosterStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.PostXeet = channel.unary_unary(
                '/Poster/PostXeet',
                request_serializer=xee__pb2.PostXeetData.SerializeToString,
                response_deserializer=xee__pb2.Empty.FromString,
                _registered_method=True)


class PosterServicer(object):
    """Missing associated documentation comment in .proto file."""

    def PostXeet(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PosterServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'PostXeet': grpc.unary_unary_rpc_method_handler(
                    servicer.PostXeet,
                    request_deserializer=xee__pb2.PostXeetData.FromString,
                    response_serializer=xee__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Poster', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('Poster', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Poster(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def PostXeet(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/Poster/PostXeet',
            xee__pb2.PostXeetData.SerializeToString,
            xee__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class AuthenticatorStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.AuthUser = channel.unary_unary(
                '/Authenticator/AuthUser',
                request_serializer=xee__pb2.AuthData.SerializeToString,
                response_deserializer=xee__pb2.AuthDetails.FromString,
                _registered_method=True)
        self.RevokeToken = channel.unary_unary(
                '/Authenticator/RevokeToken',
                request_serializer=xee__pb2.UserData.SerializeToString,
                response_deserializer=xee__pb2.Empty.FromString,
                _registered_method=True)


class AuthenticatorServicer(object):
    """Missing associated documentation comment in .proto file."""

    def AuthUser(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RevokeToken(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AuthenticatorServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'AuthUser': grpc.unary_unary_rpc_method_handler(
                    servicer.AuthUser,
                    request_deserializer=xee__pb2.AuthData.FromString,
                    response_serializer=xee__pb2.AuthDetails.SerializeToString,
            ),
            'RevokeToken': grpc.unary_unary_rpc_method_handler(
                    servicer.RevokeToken,
                    request_deserializer=xee__pb2.UserData.FromString,
                    response_serializer=xee__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Authenticator', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('Authenticator', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Authenticator(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def AuthUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/Authenticator/AuthUser',
            xee__pb2.AuthData.SerializeToString,
            xee__pb2.AuthDetails.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RevokeToken(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/Authenticator/RevokeToken',
            xee__pb2.UserData.SerializeToString,
            xee__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class RetrieverStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RetrieveFeed = channel.unary_unary(
                '/Retriever/RetrieveFeed',
                request_serializer=xee__pb2.UserData.SerializeToString,
                response_deserializer=xee__pb2.Feed.FromString,
                _registered_method=True)


class RetrieverServicer(object):
    """Missing associated documentation comment in .proto file."""

    def RetrieveFeed(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RetrieverServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RetrieveFeed': grpc.unary_unary_rpc_method_handler(
                    servicer.RetrieveFeed,
                    request_deserializer=xee__pb2.UserData.FromString,
                    response_serializer=xee__pb2.Feed.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Retriever', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('Retriever', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Retriever(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def RetrieveFeed(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/Retriever/RetrieveFeed',
            xee__pb2.UserData.SerializeToString,
            xee__pb2.Feed.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class LikerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Like = channel.unary_unary(
                '/Liker/Like',
                request_serializer=xee__pb2.LikeData.SerializeToString,
                response_deserializer=xee__pb2.LikeUpdate.FromString,
                _registered_method=True)


class LikerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Like(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_LikerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Like': grpc.unary_unary_rpc_method_handler(
                    servicer.Like,
                    request_deserializer=xee__pb2.LikeData.FromString,
                    response_serializer=xee__pb2.LikeUpdate.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Liker', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('Liker', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Liker(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Like(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/Liker/Like',
            xee__pb2.LikeData.SerializeToString,
            xee__pb2.LikeUpdate.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
